---
title: Data Visualization
linktitle: Data Visualization
toc: true
type: docs
date: "2019-05-05T00:00:00+01:00"
draft: false
menu:
  dat_sci:
    parent: I. Data Science Fundamentals
    weight: 7

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 6
---

ggplot: Used to define the canvas and set up mappings

aes(): Maps column na,es in data to visual properties such as x, y, color, fill, etc.
fill: another aes() attribute (like x and y) that can be used to change the appearance of the bar fill color
we can map columns to control the fill by categorical or continuous variables

?geom_bar
geom_label: Used to add labels to a plot
geom_smooth: Used to add a trendline
geom_smooth(method = "lm"): changes to a linear trend line (lm is the function for linear regression in R)
geom_smooth(se = FALSE): Removes the Standard Error ribbon ("hourglass")
scale_y_continuous(): Used for ajusting the Y-axis when you have continuous variable (e.g. sales)
labs(): Applies labels to ggplot's (e.g. title, subtile, x, y and caption)


Pro Tip: Alwys ungroup() after grouping and summarizing. Leaving groups can create difficult to detect errors.
ggplots are built by adding successive layers including geometries & formatting elements

+ --> used with ggplots to add (+) additional layers.

Caution: Don't use the pipe (%>%) with ggplots. Use the plus (+) 
